# fly.toml app configuration file generated for bettrdash-api-gateway"
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "monorepo-demo-web"
primary_region = "lax"

[build.args]
  PROJECT="@fly-monorepo-demo/web"
  
# api_gateway
[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 0
  processes = ["app"]
