[[services]]
name = "web api"
prefix = "/web-server"
[[services.environments]]
environment = "development"
url = "http://localhost:5001"
[[services.environments]]
environment = "production"
url = "https://monorepo-demo-web.fly.dev"

[[services]]
name = "Yoda Translater"
prefix = "/yoda"
[[services.environments]]
environment = "development"
url = "https://api.funtranslations.com"
[[services.environments]]
environment = "production"
url = "https://api.funtranslations.com"
